#' @importFrom utils modifyList
#' @noRd
.genflow_is_agent <- function(x) inherits(x, "genflow_agent")

#' @noRd
.genflow_agent_label <- function(agent) {
  agent$label %||% agent$name %||% agent$sname %||% agent$cname
}

#' @noRd
.genflow_agent_clean_fields <- function(agent) {
  args <- as.list(agent)
  args$label <- args$label %||% .genflow_agent_label(agent)
  args$name <- NULL
  args$sname <- NULL
  args$cname <- NULL
  args
}

#' @noRd
.genflow_prepare_agent_args <- function(agent,
                                        overrides,
                                        target_formals,
                                        required = character(),
                                        override_aliases = character(),
                                        override_label = "agent") {

  args <- .genflow_agent_clean_fields(agent)
  args <- .genflow_drop_null(args)

  recognized <- intersect(names(args), names(target_formals))
  base_args <- args[recognized]

  if (length(overrides)) {
    override_names <- names(overrides)
    if (is.null(override_names)) {
      override_names <- rep("", length(overrides))
    }
    if (any(!nzchar(override_names))) {
      stop("All agent overrides must be named.", call. = FALSE)
    }
    if (anyDuplicated(override_names)) {
      duplicate <- unique(override_names[duplicated(override_names)])
      stop(
        "Agent override supplied more than once: ",
        paste(duplicate, collapse = ", "),
        call. = FALSE
      )
    }

    if (length(override_aliases)) {
      if (is.null(names(override_aliases)) ||
          any(!nzchar(names(override_aliases))) ||
          any(!nzchar(override_aliases))) {
        stop("Internal error: invalid agent override aliases.", call. = FALSE)
      }
      for (alias in intersect(override_names, names(override_aliases))) {
        target <- unname(override_aliases[[alias]])
        if (target %in% override_names) {
          stop(
            "Supply only one of `", alias, "` and `", target, "`.",
            call. = FALSE
          )
        }
        names(overrides)[names(overrides) == alias] <- target
      }
      override_names <- names(overrides)
    }

    supported <- setdiff(names(target_formals), "...")
    unsupported <- setdiff(override_names, supported)
    if (length(unsupported)) {
      label <- if (identical(override_label, "agent")) {
        "agent"
      } else {
        paste0("`", override_label, "`")
      }
      stop(
        "Unsupported ", label, " override(s): ",
        paste(unsupported, collapse = ", "),
        ".",
        call. = FALSE
      )
    }
  }

  combined <- modifyList(base_args, overrides)

  if (length(required) > 0) {
    missing_required <- required[!required %in% names(combined)]
    if (length(missing_required) > 0) {
      stop(
        sprintf(
          "The agent does not provide the required field(s): %s.",
          paste(missing_required, collapse = ", ")
        ),
        call. = FALSE
      )
    }
  }

  combined
}

#' Execute a batch with a genflow agent
#'
#' Convenience wrapper that runs every batch item from one `genflow_agent`.
#' The agent is passed directly to the batch runtime; it is not copied into
#' temporary variables in `.GlobalEnv`.
#'
#' @details Parallel batches use independent PSOCK processes by default so HTTP
#'   clients are not inherited from the current R process. On Unix-like systems,
#'   `backend = "fork"` remains an explicit opt-in for fork-safe workloads.
#'   Completed per-task checkpoints remain recoverable.
#'
#' @param agent A `genflow_agent` generated by `set_agent()` or `get_agent()`.
#' @param qty Number of batch items to generate.
#' @inheritParams gen_batch
#' @param agent_prefix Optional result-label prefix. Defaults to the agent's
#'   `name`, `sname`, or "agent".
#' @param ... Additional arguments passed to `gen_batch()`.
#' @return The result of `gen_batch()`.
#' @export
gen_batch_agent <- function(agent,
                            qty = 8,
                            instructions = NULL,
                            add = NULL,
                            one_item_each = NULL,
                            add_img = NULL,
                            append = c("replace", "replace"),
                            agent_prefix = NULL,
                            directory = "content",
                            directory_img = "content",
                            log = FALSE,
                            always_fix_errors = TRUE,
                            workers = NULL,
                            backend = c("psock", "fork"),
                            add_img_each = NULL,
                            persist = TRUE,
                            verbose = TRUE,
                            checkpoint_each = NULL,
                            ...) {

  if (!.genflow_is_agent(agent)) {
    stop("`agent` must be a genflow_agent object.", call. = FALSE)
  }

  qty_int <- .genflow_positive_integer(qty, "qty")

  prefix <- agent_prefix %||% agent$name %||% agent$sname %||% "agent"

  gen_batch(
    qty = qty_int,
    instructions = instructions,
    add = add,
    one_item_each = one_item_each,
    add_img = add_img,
    append = append,
    agent_prefix = prefix,
    directory = directory,
    directory_img = directory_img,
    log = log,
    always_fix_errors = always_fix_errors,
    agent = agent,
    workers = workers,
    backend = backend,
    add_img_each = add_img_each,
    persist = persist,
    verbose = verbose,
    checkpoint_each = checkpoint_each,
    ...
  )
}
