#' @importFrom utils modifyList
#' @noRd
.genflow_is_agent <- function(x) inherits(x, "genflow_agent")

#' @noRd
.genflow_agent_label <- function(agent) {
  agent$label %||% agent$name %||% agent$sname %||% agent$cname
}

#' @noRd
.genflow_agent_clean_fields <- function(agent) {
  args <- as.list(agent)
  args$label <- args$label %||% .genflow_agent_label(agent)
  args$name <- NULL
  args$sname <- NULL
  args$cname <- NULL
  args
}

#' @noRd
.genflow_prepare_agent_args <- function(agent,
                                        overrides,
                                        target_formals,
                                        required = character()) {

  args <- .genflow_agent_clean_fields(agent)
  args <- .genflow_drop_null(args)

  recognized <- intersect(names(args), names(target_formals))
  base_args <- args[recognized]

  overrides <- overrides[names(overrides) %in% names(target_formals)]
  combined <- modifyList(base_args, overrides)

  if (length(required) > 0) {
    missing_required <- required[!required %in% names(combined)]
    if (length(missing_required) > 0) {
      stop(
        sprintf(
          "The agent does not provide the required field(s): %s.",
          paste(missing_required, collapse = ", ")
        ),
        call. = FALSE
      )
    }
  }

  combined
}

#' Execute a batch with a genflow agent
#'
#' Convenience wrapper that runs every batch item from one `genflow_agent`.
#' The agent is passed directly to the batch runtime; it is not copied into
#' temporary variables in `.GlobalEnv`.
#'
#' @details On Unix-like systems, interrupting a forked batch forcefully cleans
#'   up its child processes so blocked provider requests do not keep an R or
#'   RStudio session alive. Completed per-task checkpoints remain recoverable.
#'
#' @param agent A `genflow_agent` generated by `set_agent()` or `get_agent()`.
#' @param qty Number of batch items to generate.
#' @inheritParams gen_batch
#' @param agent_prefix Optional result-label prefix. Defaults to the agent's
#'   `name`, `sname`, or "agent".
#' @param ... Additional arguments passed to `gen_batch()`.
#' @return The result of `gen_batch()`.
#' @export
gen_batch_agent <- function(agent,
                            qty = 8,
                            instructions = NULL,
                            add = NULL,
                            one_item_each = NULL,
                            add_img = NULL,
                            append = c("replace", "replace"),
                            agent_prefix = NULL,
                            directory = "content",
                            directory_img = "content",
                            log = FALSE,
                            always_fix_errors = TRUE,
                            workers = NULL,
                            add_img_each = NULL,
                            persist = TRUE,
                            verbose = TRUE,
                            checkpoint_each = NULL,
                            ...) {

  if (!.genflow_is_agent(agent)) {
    stop("`agent` must be a genflow_agent object.", call. = FALSE)
  }

  if (!is.numeric(qty) || length(qty) != 1L || is.na(qty) || !is.finite(qty) ||
    qty < 1 || qty != as.integer(qty)) {
    stop("`qty` must be a positive integer.", call. = FALSE)
  }
  qty_int <- as.integer(qty)

  prefix <- agent_prefix %||% agent$name %||% agent$sname %||% "agent"

  gen_batch(
    qty = qty_int,
    instructions = instructions,
    add = add,
    one_item_each = one_item_each,
    add_img = add_img,
    append = append,
    agent_prefix = prefix,
    directory = directory,
    directory_img = directory_img,
    log = log,
    always_fix_errors = always_fix_errors,
    agent = agent,
    workers = workers,
    add_img_each = add_img_each,
    persist = persist,
    verbose = verbose,
    checkpoint_each = checkpoint_each,
    ...
  )
}
