#' @importFrom utils modifyList
#' @noRd
.genflow_is_agent <- function(x) inherits(x, "genflow_agent")

#' @noRd
.genflow_agent_label <- function(agent) {
  agent$label %||% agent$name %||% agent$sname %||% agent$cname
}

#' @noRd
.genflow_agent_clean_fields <- function(agent) {
  args <- as.list(agent)
  args$label <- args$label %||% .genflow_agent_label(agent)
  args$name <- NULL
  args$sname <- NULL
  args$cname <- NULL
  args
}

#' @noRd
.genflow_prepare_agent_args <- function(agent,
                                        overrides,
                                        target_formals,
                                        required = character()) {

  args <- .genflow_agent_clean_fields(agent)
  args <- .genflow_drop_null(args)

  recognized <- intersect(names(args), names(target_formals))
  base_args <- args[recognized]

  overrides <- overrides[names(overrides) %in% names(target_formals)]
  combined <- modifyList(base_args, overrides)

  if (length(required) > 0) {
    missing_required <- required[!required %in% names(combined)]
    if (length(missing_required) > 0) {
      stop(
        sprintf(
          "The agent does not provide the required field(s): %s.",
          paste(missing_required, collapse = ", ")
        ),
        call. = FALSE
      )
    }
  }

  combined
}

#' @noRd
.genflow_agent_to_batch_config <- function(agent, clone_name) {
  config <- as.list(agent)

  config$Service <- agent$service %||% agent$Service
  config$Model <- agent$model %||% agent$Model
  config$Temp <- agent$temp %||% agent$Temp
  config$Type <- agent$type %||% agent$Type %||% "Chat"
  config$Tools <- config$Tools %||% agent$tools
  config$Name <- clone_name

  config
}

#' @noRd
.genflow_assign_temp_agents <- function(prefix, qty, agent, expr) {

  assigned_names <- character(0)
  previous_values <- list()

  on.exit({
    for (nm in assigned_names) {
      if (exists(nm, envir = .GlobalEnv, inherits = FALSE)) {
        rm(list = nm, envir = .GlobalEnv)
      }
    }
    if (length(previous_values) > 0) {
      for (nm in names(previous_values)) {
        assign(nm, previous_values[[nm]], envir = .GlobalEnv)
      }
    }
  }, add = TRUE)

  for (idx in seq_len(qty)) {
    clone_name <- paste0(prefix, idx)
    if (exists(clone_name, envir = .GlobalEnv, inherits = FALSE)) {
      previous_values[[clone_name]] <- get(clone_name, envir = .GlobalEnv)
    }
    clone <- .genflow_agent_to_batch_config(agent, clone_name)
    assign(clone_name, clone, envir = .GlobalEnv)
    assigned_names <- c(assigned_names, clone_name)
  }

  eval.parent(substitute(expr))
}


#' Execute a batch with a genflow agent
#'
#' Convenience wrapper that prepares temporary agent variables so that
#' `gen_batch()` can run with a single `genflow_agent`. Any temporary variables
#' are cleaned up (and previous values restored) once the batch completes.
#'
#' @param agent A `genflow_agent` generated by `set_agent()` or `get_agent()`.
#' @param qty Number of batch items to generate.
#' @inheritParams gen_batch
#' @param agent_prefix Optional prefix used for the temporary agents. Defaults
#'   to the agent's `name`, `sname`, or "agent".
#' @param ... Additional arguments passed to `gen_batch()`.
#' @return The result of `gen_batch()`.
#' @export
gen_batch_agent <- function(agent,
                            qty = 8,
                            instructions,
                            add = NULL,
                            one_item_each = NULL,
                            add_img = NULL,
                            agent_prefix = NULL,
                            directory = "content",
                            directory_img = "content",
                            log = FALSE,
                            always_fix_errors = TRUE,
                            ...) {

  if (!.genflow_is_agent(agent)) {
    stop("`agent` must be a genflow_agent object.", call. = FALSE)
  }

  qty_int <- as.integer(qty)
  if (is.na(qty_int) || qty_int <= 0) {
    stop("`qty` must be a positive integer.", call. = FALSE)
  }

  prefix <- agent_prefix %||% agent$name %||% agent$sname %||% "agent"

  .genflow_assign_temp_agents(
    prefix = prefix,
    qty = qty_int,
    agent = agent,
    expr = gen_batch(
      qty = qty_int,
      instructions = instructions,
      add = add,
      one_item_each = one_item_each,
      add_img = add_img,
      agent_prefix = prefix,
      directory = directory,
      directory_img = directory_img,
      log = log,
      always_fix_errors = always_fix_errors,
      ...
    )
  )
}
